***FEATURE ENGINEERING***

- it is the process of tranforming raw data into features that make machine learning algorithms work better.
    - to improve performance of ML models
    - it can improve quality and relevance of features

- **Catagorical Features**

    - Groups of data
        - will include Binary Features (0 and 1)
        - sex - M F
        - Survived - Yes NO
        - Bool data type
        - Category data type -
        - Ordinal data type - you can set up a scale in the categories - Small Medium Large - COld warm hot
        - small height medium height large height

- **Numerical Features**

    - where there are numbers
    - will include float and integers both
    - continous values,
    - grouping up will not make much sense (unless doing clustering)

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
iris = sns.load_dataset('iris')

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
titanic = sns.load_dataset('titanic')

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
penguins = sns.load_dataset('penguins')
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

- Encoding

In [9]:
# label encoding
# column that you can encode

penguins['species'].unique()

# {  }

species_codes = {
    'Adelie': 0,
    'Chinstrap': 1,
    'Gentoo': 2
}

penguins['species_encoded'] = penguins['species'].map(species_codes)

penguins.sample(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male,0
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male,0
189,Chinstrap,Dream,52.0,20.7,210.0,4800.0,Male,1
312,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,Female,2
277,Gentoo,Biscoe,45.5,15.0,220.0,5000.0,Male,2
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male,0
304,Gentoo,Biscoe,44.9,13.8,212.0,4750.0,Female,2
252,Gentoo,Biscoe,45.1,14.5,207.0,5050.0,Female,2
175,Chinstrap,Dream,50.6,19.4,193.0,3800.0,Male,1
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male,2

In [3]:
# pandas map
s = pd.Series(['cat', 'cow', 'dog'])

s2 = s.map({'cat': 'kitten', 'cow': 'calf'})
print(s2)

0    kitten
1      calf
2       NaN
dtype: object

**copy and view** df df2 = df.copy() df2.dropna()

In [4]:
# inbuilt map function of python
words = ["apple", "banana", "cherry"]
lengths = map(len, words)
list(lengths)

[5, 6, 6]

In [7]:
# factorize
# species still contains the species names

# factorize will take the column and assigns to the new groups
x, y = pd.factorize(penguins['species'])

penguins [ 'species_factorized' ] = x
penguins
# penguins['species_factorize'],unique_penguins = pd.factorize(penguins['species'])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2

In [8]:
factors = pd.factorize(penguins['species'])
penguins [ 'species_factorized' ] = factors[0]
penguins [[ 'species','species_factorized' ]]

    species  species_factorized
0    Adelie                   0
1    Adelie                   0
2    Adelie                   0
3    Adelie                   0
4    Adelie                   0
..      ...                 ...
339  Gentoo                   2
340  Gentoo                   2
341  Gentoo                   2
342  Gentoo                   2
343  Gentoo                   2

[344 rows x 2 columns]

- Using the **catagories** method

In [9]:
df = penguins.copy()

df['species'] = df['species'].astype('category')

df['species_cat_encoded'] = df['species'].cat.codes
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,species_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0
...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2

**Task Exercise**
- apply the three methods to island column
- manually applying label codes
- using the factorize method
- using the category
- using the label encoder method

In [11]:
penguins['island'].unique()

# {  }

island_codes = {
    'Torgersen': 0,
    'Dream': 1,
    'Biscoe': 2
}

penguins['island_encoded'] = penguins['island'].map(island_codes)

penguins.sample(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,island_encoded
56,Adelie,Biscoe,39.0,17.5,186.0,3550.0,Female,0,2
244,Gentoo,Biscoe,42.9,13.1,215.0,5000.0,Female,2,2
169,Chinstrap,Dream,58.0,17.8,181.0,3700.0,Female,1,1
271,Gentoo,Biscoe,48.5,14.1,220.0,5300.0,Male,2,2
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male,2,2
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,Female,0,0
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0
225,Gentoo,Biscoe,46.5,13.5,210.0,4550.0,Female,2,2
162,Chinstrap,Dream,46.6,17.8,193.0,3800.0,Female,1,1
94,Adelie,Dream,36.2,17.3,187.0,3300.0,Female,0,1

In [12]:
x, y = pd.factorize(penguins['island'])

penguins [ 'island_factorized' ] = x
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,island_encoded,island_factorized
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0
...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,1
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,1
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,1
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,1
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,1

In [18]:
dfis = penguins.copy()

dfis['island'] = df['island'].astype('category')

dfis['island_cat_encoded'] = dfis['island'].cat.codes
dfis

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,island_encoded,island_factorized,island_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0,2
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0,2
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,1,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,1,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,1,0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,1,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,1,0

In [19]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

dfis['island_sklearn_le'] = encoder.fit_transform(dfis['island'])
dfis

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,island_encoded,island_factorized,island_cat_encoded,island_sklearn_le
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0,2,2
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0,2,2
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0,2,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0,2,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,1,0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,1,0,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,1,0,0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,1,0,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,1,0,0

### Label Encoding using sklearn

In [15]:
from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder instance
encoder = LabelEncoder()

df['species_sklearn_le'] = encoder.fit_transform(df['species'])
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_factorized,species_cat_encoded,species_sklearn_le
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,0
...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,2

Multiple methods:

- manual -.map() - Ordinal